spring.data.mongodb.uri=mongodb+srv://harshitArya:e8g5Vnibk7NkJPI8@cluster0.yk3nsbn.mongodb.net/busdb?appName=Cluster0

server.error.include-message=always

app.jwt.secret=YzN1cGVyLXNlY3VyZS1qd3Qtc2lnbmluZy1rZXktZm9yLWJ1cy1ib29raW5nLTIwMjY=
app.jwt.expiration-ms=86400000

app.payment.razorpay.key-id=rzp_test_SaCrn18dUYWCm1
app.payment.razorpay.key-secret=Q0c2u1YAqQDOPqCVUIMX18X1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_gmail@gmail.com
spring.mail.password=your_gmail_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=your_gmail@gmail.com